services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      webhook_mock:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=geowarns
      - DB_SSLMODE=disable
      - WEBHOOK_URL=http://webhook_mock:9090/webhook
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    networks:
      - geowarns_net
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geowarns
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./migrations/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - geowarns_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  webhook_mock:
    build:
      context: .
      dockerfile: Dockerfile.webhook_mock
    ports:
      - "9090:9090"
    networks:
      - geowarns_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  geowarns_net:
    driver: bridge
